"""Contract test: init template MUST match the locked config schema example.

Background — bugfix/2026-05-15_init-template-schema-drift:

  src/secondsight/config/template.py:_TEMPLATE is a hardcoded TOML string
  authored during config-unification (2026-05-13 task-4). The subsequent
  effort 2026-05-14_analysis-mode-toggle reshaped the schema dataclasses
  (added [general], [providers.*], [analysis.cli|sdk], etc.) and produced
  a root config.example.toml file, but the _TEMPLATE string was never updated.

  Operators running `secondsight init` got a stale config that silently
  fell through to builtin defaults for the missing sections. The diff-
  protection in write_config_if_needed() returned "up-to-date" because it
  only checks (template ⊆ existing file), not (schema ⊆ template).

  This test closes that loop. It pins the init template to the locked
  spec file. If a future schema-changing effort updates the example.toml
  but forgets the template, this test fails immediately.

Contract:
  flatten_keys(tomllib.loads(generate_config_template()))
    ==
  flatten_keys(tomllib.loads(LOCKED_EXAMPLE_PATH.read_text()))

Why key-set equality (not full text equality):
  - The init template has operator-facing header comments ("Generated by:
    secondsight init", ${VAR} usage hints) that differ from the example
    file's "LOCKED 2026-05-14" provenance header.
  - Comment / formatting drift is acceptable. Schema drift is not.
  - Key-set equality catches added sections, removed sections, renamed
    keys, and section restructure (e.g. analysis.models → analysis.cli.models).

Known limitations of this contract:
  - Does NOT catch type changes at the same key path (e.g. string → list at
    analysis.sdk.fallback_model). diff_against_template carries the same
    limitation, documented as Scar-1 in scar-reports/task-4-scar.yaml.
  - Does NOT catch default-value drift (e.g. retention.raw_traces_ttl_days
    changing 90 → 30 in the example file would not fail this test as long
    as the key still exists in both).
  - Both limitations are acceptable: type and default-value changes are
    far rarer than section additions/removals, and they break loader tests
    (test_loader_v2.py, test_schema_v2.py) directly when they happen.

If LOCKED_EXAMPLE_PATH ever moves (e.g. the changes/ folder gets archived
into docs/ after the effort closes), update the constant below to the new
canonical location. The test will surface the path failure with a clear
FileNotFoundError before anything else.
"""

from __future__ import annotations

import sys
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib  # type: ignore[import,no-reuse-dep]

from secondsight.config.template import generate_config_template

# Path to the canonical schema example, relative to repo root.
# The root example is the authored truth for the global config.toml shape.
LOCKED_EXAMPLE_PATH = Path(__file__).resolve().parents[2] / "config.example.toml"


def _flatten(data: dict, prefix: str = "") -> set[str]:
    """Recursively flatten parsed TOML into a set of dotted leaf key paths.

    Arrays and scalar values count as leaves; only dict values are recursed.
    Matches the convention used by config.template._flatten_toml().
    """
    result: set[str] = set()
    for key, value in data.items():
        full = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            result.update(_flatten(value, full))
        else:
            result.add(full)
    return result


def test_template_keys_equal_locked_example_keys() -> None:
    """The init template MUST cover exactly the locked example's key set.

    Failure modes this test catches:
      - Template is missing a section the example added (silent fallback to defaults)
      - Template has a section the example removed (operator edits obsolete keys)
      - Section restructure (analysis.models → analysis.cli.models) was not
        propagated from example to template
    """
    assert LOCKED_EXAMPLE_PATH.exists(), (
        f"Locked schema example not found at {LOCKED_EXAMPLE_PATH}. "
        f"If the effort folder was renamed/archived, update LOCKED_EXAMPLE_PATH "
        f"in this test."
    )

    template_keys = _flatten(tomllib.loads(generate_config_template()))
    example_keys = _flatten(tomllib.loads(LOCKED_EXAMPLE_PATH.read_text(encoding="utf-8")))

    missing_in_template = example_keys - template_keys
    extra_in_template = template_keys - example_keys

    detail_lines = []
    if missing_in_template:
        detail_lines.append("Keys in locked example but MISSING from template:")
        for key in sorted(missing_in_template):
            detail_lines.append(f"  - {key}")
    if extra_in_template:
        detail_lines.append("Keys in template but NOT in locked example (obsolete):")
        for key in sorted(extra_in_template):
            detail_lines.append(f"  + {key}")
    detail = "\n".join(detail_lines) if detail_lines else "(no diff)"

    assert template_keys == example_keys, (
        f"\nTemplate ↔ locked schema example drift detected.\n"
        f"Locked example: {LOCKED_EXAMPLE_PATH.name}\n"
        f"{detail}\n"
    )
