"""Dependency-light config constants shared across subsystems."""

BUILTIN_ANALYSIS_OUTPUT_REPAIR_MAX_ATTEMPTS: int = 2
BUILTIN_ANALYSIS_RETRY_FEEDBACK_MAX_CHARS: int = 1200
BUILTIN_ANALYSIS_MAX_RETRY_COUNT_CAP: int = 5

__all__ = [
    "BUILTIN_ANALYSIS_MAX_RETRY_COUNT_CAP",
    "BUILTIN_ANALYSIS_OUTPUT_REPAIR_MAX_ATTEMPTS",
    "BUILTIN_ANALYSIS_RETRY_FEEDBACK_MAX_CHARS",
]
