"""Config template generator for SecondSight (config-unification task-4).

Provides three public functions:

  generate_config_template() -> str
      Returns the complete config.toml content with comments. The template is
      the single source of truth for default values displayed to operators.

  get_template_keys() -> set[str]
      Returns the set of dotted key paths present in the template
      (e.g. ``{"retention.raw_traces_ttl_days", "analysis.default_agent", ...}``).
      Used internally by diff_against_template().

  diff_against_template(existing_path: Path) -> list[str]
      Returns key paths that are in the template but absent from the existing
      config file. Empty list means the existing config is up-to-date.

  write_config_if_needed(home: Path, *, dry_run: bool = False) -> str
      The main entry point for ``secondsight init``. Implements the four-case
      protection logic:
        1. File absent  → create it, return "generated" message.
        2. File exists, malformed TOML → return "malformed" error message, no write.
        3. File exists, all template keys present → return "up-to-date" message.
        4. File exists, new template keys missing → return diff message, no write.

Import rules (MUST NOT be violated):
    - This module must NOT import from secondsight.analysis or secondsight.sdk.
    - This module MAY import from Python stdlib only (pathlib, sys, textwrap, etc.).

Assumption documented in scar-report:
    Scar-1: diff_against_template() compares flat key-path sets. It does NOT
    detect changes to a key's TYPE (e.g. string→array). Only presence/absence
    of a key path is compared. See scar-reports/task-4-scar.yaml.
"""

from __future__ import annotations

import sys
from pathlib import Path

# tomllib is stdlib in Python 3.11+; tomli is the backport for earlier versions.
if sys.version_info >= (3, 11):
    import tomllib
else:
    try:
        import tomllib
    except ImportError:
        import tomli as tomllib  # type: ignore[import,no-reuse-dep]

__all__ = [
    "generate_config_template",
    "get_template_keys",
    "diff_against_template",
    "write_config_if_needed",
    "MSG_GENERATED",
    "MSG_MALFORMED",
    "MSG_NEW_KEYS",
    "MSG_UP_TO_DATE",
]

# ---------------------------------------------------------------------------
# Message vocabulary constants
# ---------------------------------------------------------------------------
# These constants are the single source of truth for substrings that appear
# in write_config_if_needed() return values. cli/init.py._render_text()
# imports and uses them for pattern-matching, making the coupling explicit
# and rename-safe. If you change a constant here, the matching return string
# in write_config_if_needed() MUST be updated to keep the constant a substring
# of the new message (and vice versa). The death tests in
# tests/config/test_template.py::test_death_msg_constants_* enforce this.

MSG_GENERATED = "generated"
MSG_MALFORMED = "malformed"
MSG_NEW_KEYS = "new key"
MSG_UP_TO_DATE = "up-to-date"

# ---------------------------------------------------------------------------
# Template string
# ---------------------------------------------------------------------------

_TEMPLATE = """\
# SecondSight Configuration
# Generated by: secondsight init
# 修改此檔案以覆蓋預設值。
# 使用 secondsight config validate 驗證設定。
# 使用 ~/.secondsight/.env 存放 secrets（如 ANTHROPIC_API_KEY）。
# 在此檔案中可用 ${VAR_NAME} 參照 env var。

[retention]
# 原始 hook 事件保留天數（預設 90 天）
raw_traces_ttl_days = 90
# 分析結果保留天數（預設 365 天）
analysis_ttl_days = 365
# 分析完成後是否立即清除原始事件（預設 false）
cleanup_after_analysis = false

[analysis]
# 預設 agent 類型：claude_code | codex | opencode | auto
# auto = 從最近一次 session 自動偵測
default_agent = "claude_code"

[analysis.models]
# 各 adapter 的 model 覆蓋（空字串 = 使用 adapter 預設值）
# 可使用 ${VAR_NAME} 參照 env var，例如：claude_code = "${MY_MODEL}"
claude_code = ""   # 預設: claude-haiku-4-5-20251001
codex = ""         # 必填，否則分析會失敗
opencode = ""      # 必填，否則分析會失敗

[analysis.models.fallback]
# Primary model 失敗時的 fallback chain（transport error 才觸發）
fallback_models = ["gpt-4o-mini", "gemini-2.0-flash"]

[analysis.read_project_file]
# 是否允許分析 agent 讀取專案檔案（預設啟用）
enabled = true
# 單一檔案讀取大小上限（KiB）
size_cap_kb = 256
# 額外拒絕讀取的檔案 pattern（疊加在內建 denylist 上）
denylist = []
"""


def generate_config_template() -> str:
    """Return the complete config.toml template string.

    The returned string is valid TOML and contains human-readable comments
    explaining each setting. Calling this function twice returns byte-identical
    strings (idempotent).

    Returns:
        Complete config.toml content as a string, ending with a newline.
    """
    return _TEMPLATE


# ---------------------------------------------------------------------------
# Key-path extraction
# ---------------------------------------------------------------------------


def _flatten_toml(data: dict, prefix: str = "") -> set[str]:
    """Recursively flatten a parsed TOML dict into a set of dotted key paths.

    Only leaf nodes (non-dict values) are included. Intermediate section
    names are used as path prefixes.

    Examples::
        {"retention": {"raw_traces_ttl_days": 90}} → {"retention.raw_traces_ttl_days"}
        {"analysis": {"models": {"claude_code": ""}}} → {"analysis.models.claude_code"}

    Known limitation (Scar-1): array values are included as a single key path
    regardless of their contents. Type changes (string → array) are NOT
    detected — only presence/absence of the key is compared.
    """
    result: set[str] = set()
    for key, value in data.items():
        full_key = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            result.update(_flatten_toml(value, full_key))
        else:
            result.add(full_key)
    return result


def get_template_keys() -> set[str]:
    """Return the set of dotted key paths present in the config template.

    Example return value::
        {
            "retention.raw_traces_ttl_days",
            "retention.analysis_ttl_days",
            "retention.cleanup_after_analysis",
            "analysis.default_agent",
            "analysis.models.claude_code",
            "analysis.models.codex",
            "analysis.models.opencode",
            "analysis.models.fallback.fallback_models",
            "analysis.read_project_file.enabled",
            "analysis.read_project_file.size_cap_kb",
            "analysis.read_project_file.denylist",
        }

    This set is used by diff_against_template() to detect missing keys in
    an existing config file.
    """
    parsed = tomllib.loads(_TEMPLATE)
    return _flatten_toml(parsed)


# ---------------------------------------------------------------------------
# Diff
# ---------------------------------------------------------------------------


def diff_against_template(existing_path: Path) -> list[str]:
    """Return key paths that are in the template but absent in ``existing_path``.

    Args:
        existing_path: Path to an existing, parseable config.toml. Caller is
            responsible for ensuring the file exists and is valid TOML before
            calling this function. Raises TOMLDecodeError if content is invalid.

    Returns:
        Sorted list of dotted key paths that the template defines but the
        existing file does not contain. An empty list means the existing file
        has all template keys (up-to-date).

    Known limitation (Scar-1):
        Key presence is compared by path only. A key that exists in both
        template and existing file but has a different type (e.g. string in
        template, array in existing) will NOT appear in the diff — only absent
        keys are reported.
    """
    with existing_path.open("rb") as fh:
        existing_data = tomllib.load(fh)

    template_keys = get_template_keys()
    existing_keys = _flatten_toml(existing_data)

    missing = template_keys - existing_keys
    return sorted(missing)


# ---------------------------------------------------------------------------
# Main entry point: write_config_if_needed
# ---------------------------------------------------------------------------


def write_config_if_needed(home: Path, *, dry_run: bool = False) -> str:
    """Write ~/.secondsight/config.toml if needed, with diff protection.

    Four-case logic:
        1. config.toml absent → create it (or report what would happen in dry_run).
        2. config.toml exists but malformed → return error message, do NOT write.
        3. config.toml exists, all template keys present → return up-to-date message.
        4. config.toml exists, new template keys missing → return diff message, no write.

    Args:
        home: The SecondSight home directory (e.g. ``Path.home() / ".secondsight"``).
            The function creates this directory if it does not exist (case 1 only).
        dry_run: If True, skip all writes; still compute what would happen and
            return a "would generate" message in case 1.

    Returns:
        A human-readable status message describing what was (or would be) done.
        Never raises SecondSightConfigError or TOMLDecodeError — all parse failures
        are caught and returned as an error message string so the caller can print
        it and continue (exit 0 per spec).
    """
    config_path = home / "config.toml"

    # ----- Case 1: file absent -----
    if not config_path.exists():
        if dry_run:
            # MSG_GENERATED is a substring of this message (case-insensitive).
            return f"[dry-run] would {MSG_GENERATED} {config_path} with default settings."
        home.mkdir(parents=True, exist_ok=True)
        config_path.write_text(generate_config_template(), encoding="utf-8")
        # MSG_GENERATED is a substring of this message (case-insensitive).
        return f"{MSG_GENERATED.capitalize()} {config_path} with default settings."

    # ----- File exists: attempt parse -----
    # We catch the broadest exception class here intentionally:
    # "never raise" is the contract for write_config_if_needed() so that
    # hook installation (stage 1-2) succeeds even if the config file is
    # broken. The tradeoff (sfc-2 in scar report): an I/O error (OSError)
    # would be misclassified as "malformed TOML". This is an accepted risk
    # — a malformed-TOML message is still actionable (operator checks the
    # file and discovers the I/O error), while a raised exception would
    # abort the entire init command.
    parseable = True
    try:
        with config_path.open("rb") as fh:
            tomllib.load(fh)
    except Exception:
        parseable = False

    if not parseable:
        # Case 2: malformed TOML (or I/O error — see comment above).
        # MSG_MALFORMED is a substring of this message (case-insensitive).
        return (
            f"{config_path} exists but is {MSG_MALFORMED}. "
            f"Run `secondsight config validate` for details."
        )

    # ----- Case 3 / 4: check diff -----
    # File is parseable. diff_against_template re-parses to extract key paths.
    missing_keys = diff_against_template(config_path)

    if not missing_keys:
        # Case 3: up-to-date. MSG_UP_TO_DATE is a substring of this message.
        return f"{config_path} is already {MSG_UP_TO_DATE}."

    # Case 4: new keys available — show diff, do NOT write.
    # MSG_NEW_KEYS is a substring of this message (case-insensitive).
    n = len(missing_keys)
    lines = [
        f"{config_path} has {n} {MSG_NEW_KEYS}{'s' if n != 1 else ''} available. Merge manually.",
        "New keys:",
    ]
    for key in missing_keys:
        lines.append(f"  + {key}")
    return "\n".join(lines)
